# -*- coding: utf-8 -*-
"""Stage_0_Toheeb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACoE1_mzWdPPibEN3NY3SkE4dXkendrq
"""

def get_info(Name,gmail , slack , biostack ):
  print("Hello , This is {} and my mail is {} . You can also reach me at my slack {} &  my biostack is {}".format(Name , gmail , slack , biostack))

get_info("Toheeb Damilola" ,"toheebyissa@gmail.com","@Toheeb","Drug Discovery")